# Generated by Django 3.2.7 on 2021-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='layout',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
